### ISSUE TITLE
第二章有句话感觉没有体现原文意思

### ISSUE THREAD

**Issue by haitaoy** [xiaoweiChen/Cpp_Concurrency_In_Action#12]
2.1.1 "It’s therefore essential that the copy behave equivalently to the original, or the result may not be what’s expected."
这里应该是说：会从原来的函数对象中拷贝构造一个给新线程，因此拷贝出来的对象应该和原来的对象相同，否则新线程里执行的结果可能跟预期不一样。还是我理解错了？

**Comment by xiaoweiChen** [comment]
译文中对应的是： _函数对象的副本与原始函数对象的行为是相同的，但函数对象副本得到的结果，有时却与我们的期望不同。_  这句么？

**Comment by xiaoweiChen** [comment]
和原文对比了一下，我觉得你的理解是对的。当时翻译的时候可能没有注意到。

感谢勘误，已经更新了。看一下对应的语句是不是更容易理解了 ;)
