### ISSUE TITLE
3.2.3节问题

### ISSUE THREAD

**Issue by toddyu** [xiaoweiChen/Cpp_Concurrency_In_Action#18]
3.2.3节 Option1：
大多数情况下，这种方式还不错，但有明显的缺点：需要临时构造出一个堆中类型的实例，用于接收目标值。
应该为：
大多数情况下，这种方式还不错，但有明显的缺点：需要调用者在调用前构造出一个栈中元素类型的实例，用于接收目标值。

**Comment by toddyu** [comment]
用于传入以接收返回结果

**Comment by xiaoweiChen** [comment]
这里有翻译错误，稍后会修改。
