### ISSUE TITLE
[第二章]这里的例子语法有错

### ISSUE THREAD

**Issue by garming** [xiaoweiChen/Cpp_Concurrency_In_Action#2]
使用lambda表达式也能避免这个问题。lambda表达式是C++11的一个性特性， 它允许使用一个可以捕获局部变量的局部函数（可以避免传递参数，参见2.2节）。想要具体的了解lambda表达式，可以阅读附录A的A.5节。之前的例子可以改写为lambda表达式的类型，如下：

```
std::thread my_thread([](
  do_something();
  do_something_else();
});
```

上面的例子括号没对齐，第一行最后一个应该为`{`，这里的代码应该为：

```
std::thread my_thread([]{
  do_something();
  do_something_else();
});
```

**Comment by xiaoweiChen** [comment]
我看了一下原版的pdf，这应该属于原书中的问题。不过，在e5c3af84中进行了修正。

希望能指出在翻译中的更多问题。 ;)

**Comment by garming** [comment]
处理效率挺高哦👍

**Comment by xiaoweiChen** [comment]
昨天刚好在翻译附录，就马上处理已经指出来的错误。
