### ISSUE TITLE
4.2.2 翻译的根本看不懂···

### ISSUE THREAD

**Issue by fanghaos** [xiaoweiChen/Cpp_Concurrency_In_Action#25]
4.2.2 第一段，翻译的也太差了吧，最后一句“调度器仅处理 std::packaged_task<> 实例，要比处理独立的函数高效的多。”， 原文是“This abstracts out the details of the tasks; the scheduler just deals with std::packaged_task<> instances rather than individual functions”， 哪里有高效这个词了？作者也没有隐含表达高效这一特点。
2. 第二句“这可以用在构建线程池的**建筑块**(可见第9章)，”，翻译成“构造块 结构单元”也可以啊。
3. Partial class definition竟然翻译为局部类定义！这里最起码也写成模板偏特化，或者偏特化定义。我一开始以为是嵌套类。

**Comment by xiaoweiChen** [comment]
很抱歉，书中的一些翻译不当的地方造成了阅读上的困扰。
本书是我在学习C++过程中翻译的第一本书，里面可能有很多不当的翻译或理解。
希望能谅解。

选择开源也是想借助大家的力量将这本书诠释好。若是认为我的翻译有问题，且有更好的翻译方式，可对我的库进行fork，然后提交pull request进行修改。

希望还会支持我翻译的这本书，也希望在之后收到你的pull request。 ：）

提到的语句在最新的更新中已经进行了修改。
