### ISSUE TITLE
[第一章]1.4开始入门 翻译有少了个字

### ISSUE THREAD

**Issue by garming** [xiaoweiChen/Cpp_Concurrency_In_Action#3]
ok！现在你有一个很棒的与C++11标准兼容的编译器。接下来呢？一个多线程C++程序是什么样子的？它看上去和其他C++程序差多 ==> 这里应该少了一个`不`字吧？

**Comment by xiaoweiChen** [comment]
感谢对于书中错误的反馈！ 这个问题已经在 e5c3af84 提交修复了。
