### ISSUE TITLE
3.2.3 节 选项2

### ISSUE THREAD

**Issue by lintcoder** [xiaoweiChen/Cpp_Concurrency_In_Action#33]
第二段的翻译， 个人看法：
虽然是安全的， 但并不理想。即使可以通过使用std::is_nothrow_copy_constructible 和 std::is_nothrow_move_constructible 类型特性在编译期检测到不抛出异常的拷贝构造函数或移动构造函数是否存在， 这种方法局限性也太强。因为在用户自定义的类型中，相比有着不抛出异常的拷贝构造函数或移动构造函数的类型， 那些拷贝构造函数抛出异常并且没有移动构造函数的类型往往更多（尽管这种情况可能会随着人们习惯于C++11中的右值引用而有所改变）。然而如果这些类型不能被存储在你的线程安全的栈中，想想是多么的不幸。

**Comment by xiaoweiChen** [comment]
我采纳了你翻译中的部分内容。非常感谢你提供的翻译建议！
