### ISSUE TITLE
Pages can not be opened

### ISSUE THREAD

**Issue by RaymondXiao1991** [xiaoweiChen/Cpp_Concurrency_In_Action#44]
For example,
https://chenxiaowei.gitbooks.io/cpp_concurrency_in_action/content/chapter1/1.3-chinese.html
![_ _20180620172941](https://user-images.githubusercontent.com/8736080/41649995-8c9557a0-74af-11e8-9a58-1b72f7d800d5.png)

**Comment by xiaoweiChen** [comment]
There have something wrong with page URL address.

 Your address missing a `content`.

You can try the working one. 

working address:
https://chenxiaowei.gitbooks.io/cpp_concurrency_in_action/content/content/chapter1/1.3-chinese.html
