### ISSUE TITLE
第二版出来了，还有兴趣翻译么？

### ISSUE THREAD

**Issue by cxq2003** [xiaoweiChen/Cpp_Concurrency_In_Action#47]

**Comment by xiaoweiChen** [comment]
感谢提供这个消息。从曼宁的官网看，第二版是刚出来。ref：https://www.manning.com/books/c-plus-plus-concurrency-in-action-second-edition
刚好我对C++的最新标准也十分感兴趣，如果能有办法获得免费电子版我会考虑作为2019年的翻译书籍。

**Comment by xiaoweiChen** [comment]
花了点钱(不到10RMB)，搞到了一个PDF版。我先看一下和第一版的差别。
可以期待一下在今年年终时候，这本书的翻译(如果我业余时间充裕的话)。

**Comment by l1t1** [comment]
看了下面这个，还以为中文版已经出版了 https://www.itcodemonkey.com/article/13779.html
