### ISSUE TITLE
5.2.3 std::atomic<bool> 提供的exchange()， 不仅仅是一个“读-改-写”的操作

### ISSUE THREAD

**Issue by weikano** [xiaoweiChen/Cpp_Concurrency_In_Action#49]
原文是
> exchange() isn’t the only read-modify-write operation supported by std::atomic\<bool>

翻译过来应该是
> exchange()不是std::atomic\<bool>仅有的支持“读-改-写”的方法

**Comment by xiaoweiChen** [comment]
的确，这里的翻译是有问题。已经修改了，感谢勘误啦
