### ISSUE TITLE
6.1 这被称为序列化(serialzation)： 线程轮流访问被保护的数据

### ISSUE THREAD

**Issue by weikano** [xiaoweiChen/Cpp_Concurrency_In_Action#50]
原文
> This is called serialization: threads take turns accessing the data protected by the
mutex

这里serialization翻译成串行更合适

**Comment by xiaoweiChen** [comment]
这个应该是自己在翻译的时候对 序列化 这个词的理解有误。
> 序列化是将对象状态转换为可保持或可传输的形式的过程。

改后的内容，序列化->串行化。
因为后文还有对这个过程的解释，所以个人觉得改成 串行化 更为合适。

还有，可以关注一下本书的第二版 
https://github.com/xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019 
我也已经翻译完成，其中大部分内容和第一版相同，不过在相应的地方添加了一些C++17标准的介绍。

如果有兴趣，可以去看一下。

当然，今天提到的三个issue，我也在第二版的翻译内容中进行了修改。
