### ISSUE TITLE
第五章 <C++内存模型与原子操作>  有句话读不通

### ISSUE THREAD

**Issue by NoGameNoLife00** [xiaoweiChen/Cpp_Concurrency_In_Action#9]
第五章 C++内存模型与原子操作‘了解自由排序’这一小节的第二段的这这句话
“如果你让他谢谢一个值，并且随后再问他要一个值，他要不就给你你刚告诉他的那个值，要不就是一个列表下端的值。”

这句的里面的“谢谢”应该打错了吧？

**Comment by xiaoweiChen** [comment]
已经改正，谢谢勘误。
